"""
FinTrace — Alert Model

Stores AML detection alerts with severity, type, and investigation status.
"""

import uuid
import json
from datetime import datetime, timezone
from sqlalchemy import String, DateTime, Integer, Text, ForeignKey, TypeDecorator
from sqlalchemy.orm import Mapped, mapped_column

from app.database.postgres import Base
from app.models.transaction import UUIDType, StringListType


# ── SQLite-Compatible JSON Type ───────────────────────

class JSONType(TypeDecorator):
    """Stores a dict as JSON text. Works with both PostgreSQL and SQLite."""
    impl = Text
    cache_ok = True

    def process_bind_param(self, value, dialect):
        if value is None:
            return None
        return json.dumps(value)

    def process_result_value(self, value, dialect):
        if value is None:
            return None
        return json.loads(value)


class Alert(Base):
    """An AML detection alert generated by the detection engine."""

    __tablename__ = "alerts"

    id: Mapped[str] = mapped_column(
        UUIDType(),
        primary_key=True,
        default=lambda: str(uuid.uuid4()),
    )
    # ── Alert Classification ──────────────────────────
    alert_type: Mapped[str] = mapped_column(
        String(50),
        nullable=False,
        index=True,
    )
    severity: Mapped[str] = mapped_column(
        String(10),
        nullable=False,
    )
    risk_score: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        default=0,
    )

    # ── Alert Details ─────────────────────────────────
    title: Mapped[str] = mapped_column(
        String(255),
        nullable=False,
    )
    description: Mapped[str] = mapped_column(
        Text,
        nullable=False,
    )
    accounts_involved: Mapped[list] = mapped_column(
        StringListType(),
        nullable=False,
        default=list,
    )
    evidence: Mapped[dict] = mapped_column(
        JSONType(),
        nullable=True,
    )

    # ── Investigation Status ──────────────────────────
    status: Mapped[str] = mapped_column(
        String(20),
        nullable=False,
        default="open",
    )
    assigned_to: Mapped[str] = mapped_column(
        UUIDType(),
        ForeignKey("users.id", ondelete="SET NULL"),
        nullable=True,
    )

    # ── Timestamps ────────────────────────────────────
    created_at: Mapped[datetime] = mapped_column(
        DateTime(),
        default=lambda: datetime.now(timezone.utc),
        nullable=False,
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(),
        default=lambda: datetime.now(timezone.utc),
        onupdate=lambda: datetime.now(timezone.utc),
        nullable=False,
    )

    def __repr__(self) -> str:
        return f"<Alert [{self.severity}] {self.alert_type}: {self.title}>"
